likeein/kickoff

- src/main/java/com/teamcommit/kickoff/Common/CommandMap.java
- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/webapp/WEB-INF/views/reservation/reservation.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationDetail.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationInsert.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationRequest.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationUpdate.jsp
> jaeeun "Reservation"

- src/main/webapp/WEB-INF/views/admin/boardManagement.jsp
- src/main/webapp/WEB-INF/views/admin/userManagement.jsp
- src/main/webapp/WEB-INF/views/team/team.jsp
- src/main/webapp/WEB-INF/views/team/teamApply.jsp
- src/main/webapp/WEB-INF/views/team/teamDetail.jsp
- src/main/webapp/WEB-INF/views/team/teamInsert.jsp
- src/main/webapp/WEB-INF/views/team/teamRank.jsp
- src/main/webapp/WEB-INF/views/team/teamUpdate.jsp
> yeonu update

- src/main/java/com/teamcommit/kickoff/Controller/BoardController.java
- src/main/java/com/teamcommit/kickoff/Controller/LoginController.java
- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
- src/main/webapp/WEB-INF/views/board/boardDetailWritter.jsp
- src/main/webapp/WEB-INF/views/board/boardInsert.jsp
- src/main/webapp/WEB-INF/views/board/boardReport.jsp
- src/main/webapp/WEB-INF/views/board/boardUpdate.jsp
- src/main/webapp/WEB-INF/views/login/Signup.jsp
- src/main/webapp/WEB-INF/views/login/SignupEmp.jsp
- src/main/webapp/WEB-INF/views/login/findId.jsp
- src/main/webapp/WEB-INF/views/login/findPw.jsp
- src/main/webapp/WEB-INF/views/login/loginAgree.jsp
- src/main/webapp/WEB-INF/views/login/loginAgreeEmp.jsp
> loginboard

- build.gradle
- src/main/java/com/teamcommit/kickoff/Common/AbstractDAO.java
- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Dao/ReservationDAO.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationServiceImpl.java
- src/main/resources/mapper/reservation/Reservation_SQL.xml
- src/main/webapp/WEB-INF/views/reservation/reservation.jsp
편지씁니다.
깃 우체국 아저씨,
우리 멤버들한테 잘 보내주세요:)
> oracle&reservation

- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Service/GameServiceImpl.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationServiceImpl.java
> reser, game

- src/main/resources/application.properties
- src/main/resources/mapper/board/BoardMapper.xml
- src/main/resources/mapper/helper/Helper_SQL.xml
> booReung booReung BooReureung

- src/main/java/com/teamcommit/kickoff/Controller/HelperController.java
- src/main/java/com/teamcommit/kickoff/Dao/HelperDAO.java
- src/main/java/com/teamcommit/kickoff/Do/HelperDO.java
- src/main/java/com/teamcommit/kickoff/Service/HelperService.java
- src/main/java/com/teamcommit/kickoff/Service/HelperServiceImpl.java
- src/main/webapp/WEB-INF/views/helper/helperInsert.jsp
- src/main/webapp/WEB-INF/views/helper/helperList.jsp
> helper insert

- src/main/java/com/teamcommit/kickoff/Controller/LoginController.java
- src/main/java/com/teamcommit/kickoff/Do/EmployerDO.java
- src/main/java/com/teamcommit/kickoff/Service/LoginMapper.java
- src/main/java/com/teamcommit/kickoff/Service/LoginService.java
- src/main/java/com/teamcommit/kickoff/Service/LoginServiceImpl.java
- src/main/resources/mapper/login/LoginMapper.xml
- src/main/webapp/WEB-INF/views/login/findEmp.jsp
- src/main/webapp/WEB-INF/views/login/findId.jsp
- src/main/webapp/WEB-INF/views/login/findUser.jsp
> 장연우: 아이디 찾기

- src/main/java/com/teamcommit/kickoff/Controller/TeamController.java
- src/main/java/com/teamcommit/kickoff/Do/TeamDO.java
- src/main/java/com/teamcommit/kickoff/Service/TeamService.java
- src/main/java/com/teamcommit/kickoff/Service/TeamServiceImpl.java
- src/main/resources/static/team/css/sb-admin-2.min.css
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/team/team.jsp
> 동현님 감동입니다 감동의 푸시

- src/main/resources/mapper/helper/HelperMapper.xml
> 05/13 김동현 helper insert

- src/main/java/com/teamcommit/kickoff/Controller/AdminController.java
- src/main/java/com/teamcommit/kickoff/Controller/TeamController.java
- src/main/java/com/teamcommit/kickoff/Do/UserDO.java
- src/main/java/com/teamcommit/kickoff/Service/AdminMapper.java
- src/main/java/com/teamcommit/kickoff/Service/AdminService.java
- src/main/java/com/teamcommit/kickoff/Service/AdminServiceImpl.java
- src/main/java/com/teamcommit/kickoff/Service/TeamMapper.java
- src/main/java/com/teamcommit/kickoff/Service/TeamService.java
- src/main/java/com/teamcommit/kickoff/Service/TeamServiceImpl.java
- src/main/resources/mapper/admin/Admin_SQL.xml
- src/main/resources/mapper/team/TeamMapper.xml
- src/main/resources/static/team/css/sb-admin-2.min.css
- src/main/webapp/WEB-INF/views/admin/userManagement.jsp
- src/main/webapp/WEB-INF/views/team/team.jsp
- src/main/webapp/WEB-INF/views/team/teamDetail.jsp
> 0513 team detail

- build.gradle
- src/main/java/com/teamcommit/kickoff/Controller/BoardController.java
- src/main/java/com/teamcommit/kickoff/Controller/EmpController.java
- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Do/ReservationDO.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationMapper.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationServiceImpl.java
- src/main/resources/mapper/reservation/Reservation_SQL.xml
- src/main/webapp/WEB-INF/views/reservation/reservation.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationDetail.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationInsert.jsp
> reservation&empController

- src/main/java/com/teamcommit/kickoff/Controller/MypageController.java
- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Do/PlaceDO.java
- src/main/java/com/teamcommit/kickoff/Do/ReservationDO.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationMapper.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationServiceImpl.java
- src/main/resources/mapper/reservation/Reservation_SQL.xml
- src/main/webapp/WEB-INF/views/reservation/reservationDetail.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationInsert.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationUpdate.jsp
> reservation 05/13 19:30

- src/main/java/com/teamcommit/kickoff/Controller/GameController.java
- src/main/java/com/teamcommit/kickoff/Controller/HelperController.java
- src/main/webapp/WEB-INF/views/game/game.jsp
- src/main/webapp/WEB-INF/views/game/gameScore.jsp
- src/main/webapp/WEB-INF/views/helper/helperDetail.jsp
- src/main/webapp/WEB-INF/views/helper/helperInsert.jsp
- src/main/webapp/WEB-INF/views/message/MessageInsert.jsp
> game controller

- src/main/java/com/teamcommit/kickoff/Controller/LoginController.java
- src/main/java/com/teamcommit/kickoff/Controller/TeamController.java
- src/main/java/com/teamcommit/kickoff/Do/TeamDO.java
- src/main/java/com/teamcommit/kickoff/Service/TeamMapper.java
- src/main/java/com/teamcommit/kickoff/Service/TeamService.java
- src/main/java/com/teamcommit/kickoff/Service/TeamServiceImpl.java
- src/main/resources/mapper/team/TeamMapper.xml
- src/main/resources/static/team/css/style.css
- src/main/webapp/WEB-INF/views/admin/userManagement.jsp
- src/main/webapp/WEB-INF/views/login/findId.jsp
- src/main/webapp/WEB-INF/views/login/findUser.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/team/teamInsert.jsp
- src/main/webapp/WEB-INF/views/team/teamRank.jsp
로그인 한 사용자 아이디도 잘 들어오길,, 바랍니다 ,,,
> 05/14 업체 로그인 수정

- src/main/java/com/teamcommit/kickoff/Controller/LoginController.java
- src/main/java/com/teamcommit/kickoff/Service/LoginMapper.java
- src/main/java/com/teamcommit/kickoff/Service/LoginService.java
- src/main/java/com/teamcommit/kickoff/Service/LoginServiceImpl.java
- src/main/resources/mapper/login/LoginMapper.xml
- src/main/webapp/WEB-INF/views/login/findEmp.jsp
- src/main/webapp/WEB-INF/views/login/findId.jsp
> 05/14 findId

- src/main/java/com/teamcommit/kickoff/Controller/HelperController.java
- src/main/java/com/teamcommit/kickoff/Service/HelperMapper.java
- src/main/java/com/teamcommit/kickoff/Service/HelperService.java
- src/main/java/com/teamcommit/kickoff/Service/HelperServiceImpl.java
- src/main/resources/mapper/helper/HelperMapper.xml
- src/main/resources/static/helper/css/sb-admin-2.min.css
- src/main/resources/static/helper/vendor/datatables/dataTables.bootstrap4.js
- src/main/resources/static/helper/vendor/datatables/dataTables.bootstrap4.min.js
- src/main/webapp/WEB-INF/views/helper/helperList.jsp
이거 사용하셔야 되는 분들 views/helper/helperList.jsp에 있는 스크립트 봐주세용
> 모집 상태에 따라 버튼 활성화 및 색상을 변경하는 JS

- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/resources/mapper/reservation/ReservationMapper.xml
- src/main/resources/static/reservation/css/detail.css
- src/main/webapp/WEB-INF/views/reservation/reservation.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationDetail.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationInsert.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationUpdate.jsp
> reservation 05/15 12:20

- src/main/java/com/teamcommit/kickoff/Controller/AdminController.java
- src/main/java/com/teamcommit/kickoff/Controller/TeamController.java
- src/main/resources/mapper/team/TeamMapper.xml
- src/main/resources/static/team/css/style.css
- src/main/webapp/WEB-INF/views/team/team.jsp
- src/main/webapp/WEB-INF/views/team/teamDetail.jsp
- src/main/webapp/WEB-INF/views/team/teamInsert.jsp
> 팀 게시판 글 등록

- src/main/java/com/teamcommit/kickoff/Controller/EmpController.java
- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Do/ReservationDO.java
- src/main/java/com/teamcommit/kickoff/Service/EmpMapper.java
- src/main/java/com/teamcommit/kickoff/Service/EmpService.java
- src/main/java/com/teamcommit/kickoff/Service/EmpServiceImpl.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationMapper.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationServiceImpl.java
- src/main/resources/mapper/emp/Employer_SQL.xml
- src/main/resources/mapper/reservation/ReservationMapper.xml
- src/main/resources/static/reservation/js/common.js
- src/main/resources/static/reservation/js/validation.js
- src/main/webapp/WEB-INF/views/emp/empFutsal.jsp
- src/main/webapp/WEB-INF/views/emp/empFutsalFix.jsp
- src/main/webapp/WEB-INF/views/emp/empReservation.jsp
- src/main/webapp/WEB-INF/views/emp/fixInfo.jsp
- src/main/webapp/WEB-INF/views/emp/myBoard.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationDetail.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationInsert.jsp
> emp 05/15 11:45

- src/main/java/com/teamcommit/kickoff/Controller/TeamController.java
- src/main/java/com/teamcommit/kickoff/Do/TeamDO.java
- src/main/resources/mapper/team/TeamMapper.xml
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/team/teamDetailWriter.jsp
- src/main/webapp/WEB-INF/views/team/teamInsert.jsp
- src/main/webapp/includes/footer.jsp
> 05/15 푸터 수정

- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationMapper.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationService.java
- src/main/java/com/teamcommit/kickoff/Service/ReservationServiceImpl.java
- src/main/resources/mapper/reservation/ReservationMapper.xml
- src/main/webapp/WEB-INF/views/reservation/reservationDetail.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationRequest.jsp
> reservation 05/15 13:40

- src/main/java/com/teamcommit/kickoff/Controller/BoardController.java
- src/main/resources/static/board/css/boardDetail.css
- src/main/resources/static/board/css/boardInsert.css
- src/main/resources/static/board/css/boardReport.css
- src/main/resources/static/board/css/sb-admin-2.css
- src/main/resources/static/emp/css/empFutsal/nice-select.css
- src/main/resources/static/emp/css/empFutsal/style.css
- src/main/resources/static/emp/css/fixInfo.css
- src/main/resources/static/emp/css/main.css
- src/main/resources/static/findPw/css/loginFind.css
- src/main/resources/static/findPw/css/loginFind2.css
- src/main/resources/static/game/css/boardDetail.css
- src/main/resources/static/game/css/bootstrap.min.css
- src/main/resources/static/game/css/style.css
- src/main/resources/static/game/css/styles.css
- src/main/resources/static/helper/css/helperInsert.css
- src/main/resources/static/helper/css/sb-admin-2.css
- src/main/resources/static/helper/css/style.css
- src/main/resources/static/includes/css/footer.css
- src/main/resources/static/includes/css/style.css
- src/main/resources/static/includes/css/week.css
- src/main/webapp/WEB-INF/views/board/boardDetail.jsp
> css update

- src/main/java/com/teamcommit/kickoff/Controller/EmpController.java
- src/main/java/com/teamcommit/kickoff/Controller/MypageController.java
- src/main/java/com/teamcommit/kickoff/Controller/ReservationController.java
- src/main/resources/static/emp/css/fixInfo.css
- src/main/resources/static/emp/css/main.css
- src/main/resources/static/myPage/css/main.css
- src/main/resources/static/myPage/css/myInfo.css
- src/main/resources/static/team/css/style.css
- src/main/webapp/WEB-INF/views/emp/empFutsal.jsp
- src/main/webapp/WEB-INF/views/emp/empFutsalFix.jsp
- src/main/webapp/WEB-INF/views/emp/empReservation.jsp
- src/main/webapp/WEB-INF/views/emp/fixInfo.jsp
- src/main/webapp/WEB-INF/views/emp/myBoard.jsp
- src/main/webapp/WEB-INF/views/mypage/myBoard.jsp
- src/main/webapp/WEB-INF/views/mypage/myHelper.jsp
- src/main/webapp/WEB-INF/views/mypage/myInfo.jsp
- src/main/webapp/WEB-INF/views/mypage/myMessage.jsp
- src/main/webapp/WEB-INF/views/mypage/myReservation.jsp
- src/main/webapp/WEB-INF/views/mypage/myTeam.jsp
- src/main/webapp/WEB-INF/views/reservation/reservation.jsp
- src/main/webapp/WEB-INF/views/reservation/reservationRequest.jsp
- src/main/webapp/WEB-INF/views/team/teamInsert.jsp
> myPage 05/16 12:05
